### ISSUE TITLE
importing the code

### ISSUE THREAD

**Issue by NishanthMolleti** [bazwilliams/sound-detection#2]
how do i import this code into my android application . Also how do i run it?

**Comment by bazwilliams** [comment]
I'm not sure how to develop Android applications so cannot help there. 

it is a javascript library which is targeted at nodejs. A package has been published to npmjs.com (https://www.npmjs.com/package/sound-detection) so you should be able to import this library into any nodejs application, there is an example in the README.md file (https://github.com/bazwilliams/sound-detection/blob/master/README.md#sample-app). 

Good luck!
